# Generated by Django 5.2.8 on 2025-11-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quiz_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
