# Generated by Django 5.2.8 on 2025-12-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quizresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-submitted_at']},
        ),
    ]
